Added FPM to the Start and XCVR States
Juniper MX platform has a Front Panel Display (FPM Board).  This would cause the following error when attempting to use this template.

Traceback (most recent call last):
  File "testing.py", line 48, in <module>
    result = fsm.ParseText(chassis_hardware)
  File "/mnt/c/Users/justin/network-config-backup/venv/lib/python3.8/site-packages/textfsm/parser.py", line 897, in ParseText
    self._CheckLine(line)
  File "/mnt/c/Users/justin/network-config-backup/venv/lib/python3.8/site-packages/textfsm/parser.py", line 946, in _CheckLine
    if self._Operations(rule, line):
  File "/mnt/c/Users/justin/network-config-backup/venv/lib/python3.8/site-packages/textfsm/parser.py", line 1026, in _Operations
    raise TextFSMError('State Error raised. Rule Line: %s. Input Line: %s'
textfsm.parser.TextFSMError: State Error raised. Rule Line: 16. Input Line: FPM Board        REV 04   760-059208   C1111111          Front Panel Display



Hardware inventory:
Item             Version  Part number  Serial number     Description
Chassis                                JN1111111      MX480
Midplane         REV 40   750-047862   A111111          Enhanced MX480 Midplane
FPM Board        REV 04   760-059208   1111111          Front Panel Display
PEM 0            Rev 01   740-063046   Q111111111       PS 1.4-2.52kW; 90-264V AC in
PEM 1            Rev 01   740-063046   QC11111111       PS 1.4-2.52kW; 90-264V AC in
PEM 2            Rev 01   740-063046   QC11111111       PS 1.4-2.52kW; 90-264V AC in
PEM 3            Rev 01   740-063046   QC11111111       PS 1.4-2.52kW; 90-264V AC in
Routing Engine 0 REV 03   740-051822   911111111        RE-S-1800x4
Routing Engine 1 REV 03   740-051822   901111111        RE-S-1800x4
CB 0             REV 07   750-062572   C1111111        Enhanced MX SCB 2
CB 1             REV 08   750-055976   C1111111        Enhanced MX SCB 2
FPC 0            REV 24   750-054902   C1111111          MPC3E NG PQ & Flex Q
  CPU            REV 13   711-045719   C1111111         RMPC PMB
  MIC 0          REV 35   750-028392   C111111          3D 20x 1GE(LAN) SFP
    PIC 0                 BUILTIN      BUILTIN           10x 1GE(LAN) SFP
      Xcvr 0     REV 02   740-013111   1111111           SFP-T
  ...